import type { Question } from '../types'

export const QUESTIONS: Question[] = [
  {
    id: 0,
    text: 'How often do you exercise or go for a walk?',
    options: [
      { emoji: '🚶', label: 'Every day', sublabel: 'Daily walk or exercise', score: -2 },
      { emoji: '🏋️', label: 'A few times a week', sublabel: '3 to 5 times a week', score: -1 },
      { emoji: '🌿', label: 'Once in a while', sublabel: 'A few times a month', score: 2 },
      { emoji: '🛋️', label: 'Rarely or never', sublabel: 'Mostly sitting at home', score: 3 },
    ],
    greenBadge: '🚶 Active body',
    redBadge: '🛋️ Move more',
    tip: 'Try a 20-minute walk 3 times a week — your body will feel the difference!',
  },
  {
    id: 1,
    text: 'How many hours do you sleep each night?',
    options: [
      { emoji: '🌟', label: '8 hours or more', sublabel: 'Wake up feeling rested', score: -2 },
      { emoji: '😊', label: '7 to 8 hours', sublabel: 'Sleep is mostly good', score: -1 },
      { emoji: '🥱', label: '5 to 6 hours', sublabel: 'Wake up a little tired', score: 2 },
      { emoji: '😩', label: 'Less than 5 hours', sublabel: 'Feel very tired every day', score: 3 },
    ],
    greenBadge: '😴 Good sleep',
    redBadge: '😴 Sleep more',
    tip: 'Going to bed 30 minutes earlier each night can make a big difference!',
  },
  {
    id: 2,
    text: 'What does your daily food look like?',
    options: [
      { emoji: '🌿', label: 'Very healthy', sublabel: 'Fruits, vegetables, home food', score: -2 },
      { emoji: '🥗', label: 'Mostly healthy', sublabel: 'Good food most days', score: -1 },
      { emoji: '🍱', label: 'Mix of healthy and oily', sublabel: 'Sometimes fried or spicy food', score: 2 },
      { emoji: '🍔', label: 'Mostly oily or junk food', sublabel: 'Fried, packaged, or fast food', score: 3 },
    ],
    greenBadge: '🥗 Healthy eater',
    redBadge: '🍔 Eat better',
    tip: 'Adding one extra serving of vegetables a day makes a real difference!',
  },
  {
    id: 3,
    text: 'Do you smoke or use tobacco?',
    options: [
      { emoji: '🚫', label: 'Never', sublabel: 'Never smoked or used tobacco', score: -2 },
      { emoji: '☁️', label: 'Very rarely', sublabel: 'Only on rare occasions', score: -1 },
      { emoji: '🙈', label: 'Trying to stop', sublabel: 'Want to quit', score: 2 },
      { emoji: '🚬', label: 'Yes, every day', sublabel: 'Daily habit', score: 3 },
    ],
    greenBadge: '🫁 Healthy lungs',
    redBadge: '🚬 Quit smoking',
    tip: 'Every smoke-free day adds healthy years to your life — keep going!',
  },
  {
    id: 4,
    text: 'How much stress or tension do you feel?',
    options: [
      { emoji: '🧘', label: 'Rarely stressed', sublabel: 'Mostly calm and at peace', score: -2 },
      { emoji: '😌', label: 'Sometimes stressed', sublabel: 'Manageable most of the time', score: -1 },
      { emoji: '😟', label: 'Often stressed', sublabel: 'Worry or tension is common', score: 2 },
      { emoji: '😤', label: 'Always stressed', sublabel: 'Tension almost every day', score: 3 },
    ],
    greenBadge: '🧘 Low stress',
    redBadge: '😤 Relax more',
    tip: 'Even 5 minutes of slow, deep breathing each day can reduce stress a lot!',
  },
  {
    id: 5,
    text: 'How many glasses of water do you drink each day?',
    options: [
      { emoji: '💧', label: '6 or more glasses', sublabel: 'Drink water regularly', score: -2 },
      { emoji: '🥤', label: '3 to 5 glasses', sublabel: 'Drink a decent amount', score: -1 },
      { emoji: '😐', label: '1 to 2 glasses', sublabel: 'Not drinking enough', score: 2 },
      { emoji: '🏜️', label: 'Barely any', sublabel: 'Drink very little water', score: 3 },
    ],
    greenBadge: '💧 Well hydrated',
    redBadge: '💧 Drink more water',
    tip: 'Keep a glass of water on the table — you will drink more without even trying!',
  },
  {
    id: 6,
    text: 'How is your energy level during the day?',
    options: [
      { emoji: '⚡', label: 'Full of energy all day', sublabel: 'Feel active and strong', score: -2 },
      { emoji: '😊', label: 'Good energy mostly', sublabel: 'No big tiredness', score: -1 },
      { emoji: '😐', label: 'Often feel tired', sublabel: 'Get tired easily', score: 2 },
      { emoji: '😴', label: 'Exhausted all day', sublabel: 'Very low energy every day', score: 3 },
    ],
    greenBadge: '⚡ Good energy',
    redBadge: '😴 Boost energy',
    tip: 'A short morning walk can give you energy for the whole day!',
  },
  {
    id: 7,
    text: 'How often do you drink alcohol?',
    options: [
      { emoji: '🚫', label: 'Never', sublabel: 'Do not drink at all', score: -2 },
      { emoji: '🎉', label: 'Only on special occasions', sublabel: 'Festivals or family events', score: -1 },
      { emoji: '🥂', label: 'Most weekends', sublabel: 'A few times a week', score: 2 },
      { emoji: '🍷', label: 'Almost every day', sublabel: 'Daily or near-daily drinking', score: 3 },
    ],
    greenBadge: '🍃 No alcohol',
    redBadge: '🍷 Drink less',
    tip: 'Cutting back on alcohol even a little protects your heart and liver!',
  },
  {
    id: 8,
    text: 'How do you feel emotionally most days?',
    options: [
      { emoji: '🌈', label: 'Happy and positive', sublabel: 'Feel good most of the time', score: -2 },
      { emoji: '😊', label: 'Mostly okay', sublabel: 'Generally in a good mood', score: -1 },
      { emoji: '😐', label: 'Up and down', sublabel: 'Mood changes day to day', score: 2 },
      { emoji: '😞', label: 'Often sad or low', sublabel: 'Feeling down most days', score: 3 },
    ],
    greenBadge: '🌈 Happy mind',
    redBadge: '💜 Take care of mood',
    tip: 'Even 10 minutes of sunlight in the morning can lift your mood noticeably!',
  },
]
