import type { Question } from '../types'

export const QUESTIONS: Question[] = [
  {
    id: 0,
    text: 'How often do you move your body?',
    options: [
      { emoji: '⚡', label: 'Every single day', sublabel: "Can't stop, won't stop", score: -2 },
      { emoji: '🏋️', label: 'A few times a week', sublabel: '3–5 sessions', score: -1 },
      { emoji: '🚶', label: 'Occasionally', sublabel: 'Light walks here and there', score: 2 },
      { emoji: '🛋️', label: 'Mostly chill', sublabel: 'I love my couch', score: 3 },
    ],
    greenBadge: '⚡ Active body',
    redBadge: '🛋️ Move more',
    tip: 'Try a 20-min walk 3x a week — your future self will thank you!',
  },
  {
    id: 1,
    text: 'How well do you sleep?',
    options: [
      { emoji: '🌟', label: '8+ hrs, always fresh', sublabel: 'Wake up glowing', score: -2 },
      { emoji: '😊', label: 'A solid 7–8 hrs', sublabel: 'Pretty good most nights', score: -1 },
      { emoji: '🥱', label: '5–6 hrs', sublabel: 'Could be better', score: 2 },
      { emoji: '😩', label: 'Under 5 hrs', sublabel: 'Running on empty', score: 3 },
    ],
    greenBadge: '😴 Great sleeper',
    redBadge: '😴 Sleep more',
    tip: 'Try sleeping 30 mins earlier tonight — even small changes help a lot!',
  },
  {
    id: 2,
    text: "How's your food mostly?",
    options: [
      { emoji: '🌿', label: 'Very clean', sublabel: 'Whole foods, barely processed', score: -2 },
      { emoji: '🥗', label: 'Mostly healthy', sublabel: 'Good choices most days', score: -1 },
      { emoji: '🍱', label: 'Mix of both', sublabel: 'Healthy-ish', score: 2 },
      { emoji: '🍔', label: 'Mostly junk', sublabel: "Fast food is my love language", score: 3 },
    ],
    greenBadge: '🥗 Healthy eater',
    redBadge: '🍔 Eat better',
    tip: 'Add one extra serving of vegetables per day — it makes a real difference!',
  },
  {
    id: 3,
    text: 'Do you smoke?',
    options: [
      { emoji: '🚫', label: 'Never', sublabel: "Never touched one", score: -2 },
      { emoji: '☁️', label: 'Occasionally', sublabel: 'Social only, rarely', score: -1 },
      { emoji: '🙈', label: 'Trying to quit', sublabel: "Working on it", score: 2 },
      { emoji: '🚬', label: 'Yes, regularly', sublabel: 'Daily habit', score: 3 },
    ],
    greenBadge: '🫁 Clean lungs',
    redBadge: '🚬 Quit smoking',
    tip: 'Every cigarette-free day adds time back to your life — keep going!',
  },
  {
    id: 4,
    text: 'How stressed are you usually?',
    options: [
      { emoji: '🧘', label: 'Rarely stressed', sublabel: 'Zen mode: on', score: -2 },
      { emoji: '😌', label: 'Sometimes', sublabel: 'Manageable most days', score: -1 },
      { emoji: '😟', label: 'Pretty often', sublabel: 'Always something going on', score: 2 },
      { emoji: '😤', label: 'Always stressed', sublabel: 'Stress is my default', score: 3 },
    ],
    greenBadge: '🧘 Low stress',
    redBadge: '😤 Stress less',
    tip: 'Even 5 mins of deep breathing daily can lower your stress significantly!',
  },
  {
    id: 5,
    text: 'How much water do you drink daily?',
    options: [
      { emoji: '🌊', label: '6+ glasses', sublabel: 'Hydration queen', score: -2 },
      { emoji: '💧', label: '3–5 glasses', sublabel: 'Doing alright', score: -1 },
      { emoji: '🥤', label: '1–2 glasses', sublabel: 'Not enough', score: 2 },
      { emoji: '🏜️', label: 'Barely any', sublabel: 'Running dry', score: 3 },
    ],
    greenBadge: '💧 Well hydrated',
    redBadge: '💧 Drink more water',
    tip: "Keep a water bottle visible — you'll drink 40% more without even thinking!",
  },
  {
    id: 6,
    text: "How's your energy through the day?",
    options: [
      { emoji: '⚡', label: 'Always energetic', sublabel: 'Full battery all day', score: -2 },
      { emoji: '😊', label: 'Pretty good', sublabel: 'No major crashes', score: -1 },
      { emoji: '😐', label: 'Often low', sublabel: 'Afternoon slump hits hard', score: 2 },
      { emoji: '😴', label: 'Always tired', sublabel: 'Exhausted by noon', score: 3 },
    ],
    greenBadge: '⚡ High energy',
    redBadge: '😴 Boost energy',
    tip: 'A 10-min morning walk can boost your energy for the whole day!',
  },
  {
    id: 7,
    text: 'How often do you drink alcohol?',
    options: [
      { emoji: '🚫', label: 'Never', sublabel: "Don't drink at all", score: -2 },
      { emoji: '🎉', label: 'Rarely', sublabel: 'Special occasions only', score: -1 },
      { emoji: '🥂', label: 'Most weekends', sublabel: 'Weekend ritual', score: 2 },
      { emoji: '🍷', label: 'Most days', sublabel: 'Daily glass or more', score: 3 },
    ],
    greenBadge: '🍃 Alcohol-free',
    redBadge: '🍷 Drink less',
    tip: 'Try 2 alcohol-free days per week — your liver (and skin!) will love it.',
  },
  {
    id: 8,
    text: "How's your mood generally?",
    options: [
      { emoji: '🌈', label: 'Almost always great', sublabel: 'Life is beautiful', score: -2 },
      { emoji: '😊', label: 'Pretty happy', sublabel: 'Good vibes mostly', score: -1 },
      { emoji: '😐', label: 'Up and down', sublabel: 'Depends on the day', score: 2 },
      { emoji: '😞', label: 'Often low', sublabel: "Tough stretch lately", score: 3 },
    ],
    greenBadge: '🌈 Happy mind',
    redBadge: '💜 Nurture mood',
    tip: 'Even 10 mins of sunlight in the morning can lift your mood noticeably!',
  },
]
